/**
 * Created by ycn-1 on 4/4/2018.
 */
var ADMINISTRATOR_LEVEL = 2;
var GENERAL_DEALER_LEVEL = 1;

exports.GENERAL_DEALER_LEVEL = GENERAL_DEALER_LEVEL;
exports.ADMINISTRATOR_LEVEL = ADMINISTRATOR_LEVEL;