/**
 * Created by ycn-1 on 4/4/2018.
 */
var ADMINISTRATOR_LEVEL = 2;
var GENERAL_DEALER_LEVEL = 1;

var ERROR_DATABASE_CONNECTION = 10;
var ERROR_JSON_PARSE = 11;
var ERROR_NO_DATA = 12;
var ERROR_NO_SATISFACTION_QUERY = 13;

exports.GENERAL_DEALER_LEVEL = GENERAL_DEALER_LEVEL;
exports.ADMINISTRATOR_LEVEL = ADMINISTRATOR_LEVEL;

exports.ERROR_DATABASE_CONNECTION = ERROR_DATABASE_CONNECTION;
exports.ERROR_JSON_PARSE = ERROR_JSON_PARSE;
exports.ERROR_NO_DATA = ERROR_NO_DATA;
exports.ERROR_NO_SATISFACTION_QUERY = ERROR_NO_SATISFACTION_QUERY;
